### ISSUE TITLE
Feature Request: Add Timeout for subprocess.run()

### ISSUE THREAD

**Issue by martinclauss** [joaompinto/pystrace#1]
Hello :)

Would it be possible to add a user-defined timeout to `subprocess.run()` in https://github.com/joaompinto/pystrace/blob/11604e41bab3d2651a865b925a7099b32520c24c/pystrace/tracer.py#L103 so that I can trace programs that do not terminate quickly (e.g. long running programs or daemon-like programs). On the command line you can always Ctrl+C to terminate the tracing.

Thanks!

Kind regards
Martin

**Comment by joaompinto** [comment]
Fixed in v0.0.3, thanks for the improvement suggestion.
