### ISSUE TITLE
`Tracer.run()` hangs indefinitely

### ISSUE THREAD

**Issue by jstucke** [joaompinto/pystrace#2]
If the return code of the program is negative (in my case it was "-11" after a SIGSEGV), `handle_strace_data()` will hang indefinitely in the `while True:` loop because `str.isnumeric()` only works with positive numbers.

Easy fix: using `lstrip`: `data.lstrip("-").isnumeric()`

**Comment by joaompinto** [comment]
Hi,  thanks for reporting it. I will try to provide a fix version soon.

**Comment by jstucke** [comment]
Thank you for the quick fix!
